{
  ### Environment Parameters
  mode: inference,
  cuda: true,
  pin_memory: true,
  wandb: false,
  worker: 2,
  CUDA_VISIBLE_DEVICES: '0',

  ### Train Parameters
  model_name: 'neUNet',
  inference_mode: 'segmentation',
  task: 'segmentation',
  inference_level: 100,
  dataloader: 'Image2Image_zero_pad',
  num_class: 2,
  criterion: 'DiceBCE',
  input_space: 'RGB',
  input_channel: 3,
  input_size: [608, 608],  # DRIVE:608, STARE:704, CHASEDB1:1024

  model_path: 'pretrained/neUNet_DRIVE.pt',
  val_x_path: '/path/to/your/dataset/val/input',
  val_y_path: '/path/to/your/dataset/val/label',
}
